version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      - run:
          name: Install pytest
          command: pip install pytest

      - run:
          name: Run main.py
          command: python main.py

      - run:
          name: Run tests
          command: python test.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
